version: "3"

services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbit-ecommercemm
        environment:
            RABBITMQ_DEFAULT_USER: "ecommercemm"
            RABBITMQ_DEFAULT_PASS: "ecommercemm"
        ports: 
            - "5672:5672"
            - "15672:15672"

    sql-server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: ecommercemm-sqlserver
        build: 
            context: ../sql
            dockerfile: ./Dockerfile
        environment:
            SA_PASSWORD: "MeuDB@123"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
            MSSQL_USER: sa
        ports:
        - "1433:1433"

    web-mvc:
        image: ecommercemm-web-mvc-ecommerce:latest
        container_name: ecommercemm-web-mvc-ecommerce
        build:
            context: ../src
            dockerfile: ./Web/MVC/WebMVC/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=http://+:5001
        ports: 
            - "5001:5001"
        depends_on:
            - api-catalogo
            - api-identidade
            - api-cliente
            - api-bff-compras
            
    api-identidade:
        image: ecommercemm-api-identidade:latest
        container_name: ecommercemm-api-identidade
        build:
            context: ../src
            dockerfile: ./Services/Identidade.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5101;http://+5102
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5102:5102"
            - "5101:5101"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            
    api-carrinho:
        image: ecommercemm-api-carrinho:latest
        container_name: ecommercemm-api-carrinho
        build:
            context: ../src
            dockerfile: ./Services/Carrinho.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5201;http://+5202
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5202:5202"
            - "5201:5201"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server
            
    api-catalogo:
        image: ecommercemm-api-catalogo:latest
        container_name: ecommercemm-api-catalogo
        build:
            context: ../src
            dockerfile: ./Services/Catalogo.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5301;http://+5302
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5302:5302"
            - "5301:5301"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - sql-server
            
    api-cliente:
        image: ecommercemm-api-cliente:latest
        container_name: ecommercemm-api-cliente
        build:
            context: ../src
            dockerfile: ./Services/Cliente.API/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5401;http://+5402
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5402:5402"
            - "5401:5401"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server
            
    api-bff-compras:
        image: ecommercemm-api-bff-compras:latest
        container_name: ecommercemm-api-bff-compras
        build:
            context: ../src
            dockerfile: ./ApiGateways/Bff.Compras/Dockerfile
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5501;http://+5502
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5502:5502"
            - "5501:5501"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - api-carrinho
            - api-pagamento
            - api-pedido
            
    api-pagamento:
        image: ecommercemm-api-pagamento:latest
        container_name: ecommercemm-api-pagamento
        build:
            context: ../src
            dockerfile: ./Services/Pagamentos.API/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:501;http://+5602
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5602:5602"
            - "5601:5601"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - api-pedido
            - sql-server
            
    api-pedido:
        image: ecommercemm-api-pedido:latest
        container_name: ecommercemm-api-pedido
        build:
            context: ../src
            dockerfile: ./Services/Pedidos.API/Dockerfile
        restart: always
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:5701;http://+5702
            - ASPNETCORE_Kestrel__Certificates__Default__Password=florattaboutique
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/florattaboutique-certificate.pfx
        ports: 
            - "5702:5702"
            - "5701:5701"
        volumes:
            - ./certs:/https:ro
        depends_on:
            - rabbitmq
            - api-identidade
            - sql-server
            
    ecommercemm-server:
        image: ecommercemm-server:latest
        container_name: ecommercemm-server
        build:
            context: ./
            dockerfile: ./nginx/Dockerfile
        ports: 
            - "80:80"
            - "443:443"
        depends_on:
            - web-mvc